#!/usr/bin/env bash
# =============================================================================
# setup_hpc.sh — Virtual environment setup for HPC clusters (CINECA & others)
#
# This script configures a Python environment on HPC clusters, placing the
# virtual environment in fast scratch storage (not the slow $HOME directory).
#
# IMPORTANT: Run this script AFTER loading the right software modules:
#
#   module load profile/deeplrn          # CINECA deep-learning profile
#   module load cuda/11.8                # (or cuda/12.1 if available)
#   module load python/3.10.8-gcc11.3    # (or your cluster's Python version)
#   bash setup_hpc.sh
#
# Scratch storage resolution order (to avoid $HOME quota limits):
#   1. $CINECA_SCRATCH — CINECA's dedicated fast storage (priority)
#   2. $WORK               — Generic HPC work directory
#   3. $SCRATCH            — Generic temporary scratch space
#   4. Current directory   — Last resort if none above are available
#
# =============================================================================
set -euo pipefail

# ── Source shared utilities ────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/scripts/utils.sh"

# ── Resolve best storage location for venv ─────────────────────────────────
# Prefer fast HPC scratch storage; avoid $HOME (small quota, slow I/O)

if [[ -n "${CINECA_SCRATCH:-}" ]]; then
    HPC_SCRATCH="$CINECA_SCRATCH"
    echo "==> Using CINECA_SCRATCH: $HPC_SCRATCH"
elif [[ -n "${WORK:-}" ]]; then
    HPC_SCRATCH="$WORK"
    echo "==> Using WORK directory: $HPC_SCRATCH"
elif [[ -n "${SCRATCH:-}" ]]; then
    HPC_SCRATCH="$SCRATCH"
    echo "==> Using SCRATCH directory: $HPC_SCRATCH"
else
    HPC_SCRATCH="$(pwd)"
    echo "⚠️  WARNING: No HPC scratch variable found; using project directory"
fi

PROJECT_NAME="jet_anomaly"
VENV_DIR="${HPC_SCRATCH}/${PROJECT_NAME}_venv"

echo "═══════════════════════════════════════════════════════════════════"
echo "  HPC Python Environment Setup"
echo "═══════════════════════════════════════════════════════════════════"
echo "==> Venv location: ${VENV_DIR}"

# ── Verify Python comes from loaded modules ────────────────────────────────
echo "==> Verifying Python from loaded modules…"
PYTHON_PATH=$(verify_python)

# ── Create venv with system packages inheritance ────────────────────────────
# --system-site-packages allows inheriting CUDA-aware packages from HPC modules
# (mpi4py, cuDNN, etc.) without reinstalling; remove this flag if you need isolation

echo "==> Creating virtual environment with --system-site-packages"
create_venv "$VENV_DIR" --system-site-packages

# Save venv path for later use
echo "VENV_DIR=${VENV_DIR}" > .venv_path
echo "==> Venv path saved to .venv_path"

# ── Activate venv ──────────────────────────────────────────────────────────
source "$VENV_DIR/bin/activate"

echo "==> Upgrading pip / wheel / setuptools"
pip install --quiet --upgrade pip wheel setuptools

# ── Detect CUDA and install PyTorch if needed ──────────────────────────────
echo "==> Checking for PyTorch in system modules…"

if python -c "import torch" &>/dev/null; then
    echo "✓ PyTorch already available from system modules"
    python -c "import torch; print(f'  Version: {torch.__version__}'); print(f'  CUDA: {torch.version.cuda if hasattr(torch, \"version\") else \"N/A\"}')"
else
    CUDA=$(detect_cuda)
    echo "==> PyTorch not in system modules; installing for ${CUDA}"
    install_pytorch "$CUDA"
fi

# ── Install remaining dependencies (excluding torch/torchvision) ────────────
echo "==> Installing project requirements"
install_requirements torch torchvision

# ── Create activation helper script ────────────────────────────────────────
# This can be sourced from anywhere in the project to activate the venv

cat > activate_env.sh <<ACTIVATE_SCRIPT
#!/usr/bin/env bash
# Auto-generated by setup_hpc.sh — do NOT edit manually
# Usage: source activate_env.sh

VENV_DIR="${VENV_DIR}"

if [[ ! -f "\${VENV_DIR}/bin/activate" ]]; then
    echo "ERROR: venv not found at \${VENV_DIR}" >&2
    echo "Re-run setup_hpc.sh on the login node first." >&2
    exit 1
fi

# shellcheck disable=SC1091
source "\${VENV_DIR}/bin/activate"
echo "✓ Activated venv: \${VENV_DIR}"
ACTIVATE_SCRIPT

chmod +x activate_env.sh
echo "==> Activation helper created: activate_env.sh"

# ── Verify installation ────────────────────────────────────────────────────
verify_installation

echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║  ✓  HPC Setup complete!                                           ║"
echo "╠═══════════════════════════════════════════════════════════════════╣"
echo "║  Activate environment:                                            ║"
echo "║    source activate_env.sh                                         ║"
echo "║  OR                                                               ║"
echo "║    source ${VENV_DIR}/bin/activate                 ║"
echo "║                                                                   ║"
echo "║  Submit training job:                                             ║"
echo "║    sbatch submit_job.sh                                           ║"
echo "║                                                                   ║"
echo "║  Submit with data skip (if already downloaded):                   ║"
echo "║    sbatch --export=ALL,SKIP_PREPROCESS=1 submit_job.sh           ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
