#!/usr/bin/env bash
# =============================================================================
# setup_hpc.sh — Virtual environment setup for HPC clusters (CINECA & others)
#
# IMPORTANT: Run this script AFTER loading the right modules on the login node:
#
#   module load profile/deeplrn          # CINECA deep-learning profile
#   module load cuda/11.8                # or cuda/12.1
#   module load python/3.10.8-gcc11.3    # or the version available on your cluster
#   bash setup_hpc.sh
#
# The venv is placed in $CINECA_SCRATCH (fast parallel storage at CINECA).
# If $CINECA_SCRATCH is not defined (other HPCs), it falls back to $WORK,
# then $SCRATCH, then the project directory itself.
# =============================================================================
set -euo pipefail

# ── Resolve best storage location ─────────────────────────────────────────────
# Prefer fast scratch/work storage; avoid $HOME (small quota, slow I/O on HPC)
if [[ -n "${CINECA_SCRATCH:-}" ]]; then
    HPC_SCRATCH="$CINECA_SCRATCH"
elif [[ -n "${WORK:-}" ]]; then
    HPC_SCRATCH="$WORK"
elif [[ -n "${SCRATCH:-}" ]]; then
    HPC_SCRATCH="$SCRATCH"
else
    HPC_SCRATCH="$(pwd)"          # last resort: project directory
    echo "WARNING: No HPC scratch variable found; placing venv in project dir."
fi

PROJECT_NAME="jet_anomaly"
VENV_DIR="${HPC_SCRATCH}/${PROJECT_NAME}_venv"

echo "==> HPC scratch  : ${HPC_SCRATCH}"
echo "==> Venv location: ${VENV_DIR}"

# ── Guard: ensure python3 is from the loaded module, not /usr/bin ─────────────
PYTHON=$(command -v python3 || command -v python)
PYTHON_VERSION=$("$PYTHON" --version 2>&1)
echo "==> Using Python : ${PYTHON_VERSION} (${PYTHON})"

# ── Create venv ───────────────────────────────────────────────────────────────
# --system-site-packages lets the venv inherit HPC-provided packages
# (CUDA-aware mpi4py, cuDNN, etc.) without reinstalling them.
# Remove that flag if you want a fully isolated environment.
echo "==> Creating virtual environment at ${VENV_DIR}"
"$PYTHON" -m venv --system-site-packages --copies "$VENV_DIR"

# Write the venv path to a local dotfile so scripts can source it automatically
echo "VENV_DIR=${VENV_DIR}" > .venv_path
echo "==> Venv path written to .venv_path"

# ── Activate ──────────────────────────────────────────────────────────────────
# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

echo "==> Upgrading pip / wheel / setuptools"
pip install --quiet --upgrade pip wheel setuptools

# ── Detect CUDA version from loaded module (nvidia-smi is available on login nodes) ──
detect_cuda_wheel() {
    if ! command -v nvidia-smi &>/dev/null; then
        # Fall back to CUDA module name if nvidia-smi not on login node
        if   module list 2>&1 | grep -q "cuda/12"; then echo "cu121"
        elif module list 2>&1 | grep -q "cuda/11"; then echo "cu118"
        else echo "cpu"; fi
        return
    fi
    local ver
    ver=$(nvidia-smi | grep -oP "CUDA Version: \K[0-9]+\.[0-9]+" 2>/dev/null || echo "")
    if   [[ "$ver" == 12.* ]]; then echo "cu121"
    elif [[ "$ver" == 11.* ]]; then echo "cu118"
    else echo "cpu"; fi
}

CUDA_WHEEL=${CUDA_WHEEL:-$(detect_cuda_wheel)}
echo "==> PyTorch wheel target: ${CUDA_WHEEL}"

# ── PyTorch ───────────────────────────────────────────────────────────────────
# Skip if already provided by the HPC module (check with: python -c "import torch")
if python -c "import torch" &>/dev/null; then
    echo "==> torch already available from system modules — skipping pip install"
    python -c "import torch; print(f'   torch {torch.__version__}, CUDA={torch.version.cuda}')"
else
    if [[ "$CUDA_WHEEL" == "cpu" ]]; then
        pip install --quiet "torch>=2.0.0" "torchvision>=0.15.0"
    else
        pip install --quiet \
            "torch>=2.0.0" "torchvision>=0.15.0" \
            --index-url "https://download.pytorch.org/whl/${CUDA_WHEEL}"
    fi
fi

# ── Remaining dependencies ─────────────────────────────────────────────────────
echo "==> Installing project requirements (excluding torch/torchvision)"
# Filter out torch lines to avoid version conflicts with system-provided torch
grep -v -E "^torch" requirements.txt | pip install --quiet -r /dev/stdin

# ── Write activation helper script ────────────────────────────────────────────
# Source this tiny helper anywhere in the project tree instead of hardcoding
# the full venv path.
cat > activate_env.sh <<ACTIVATE
#!/usr/bin/env bash
# Auto-generated by setup_hpc.sh — do NOT edit manually.
# Usage:  source activate_env.sh
VENV_DIR="${VENV_DIR}"
if [[ -f "\${VENV_DIR}/bin/activate" ]]; then
    source "\${VENV_DIR}/bin/activate"
    echo "Activated venv: \${VENV_DIR}"
else
    echo "ERROR: venv not found at \${VENV_DIR}. Re-run setup_hpc.sh."
    exit 1
fi
ACTIVATE

echo "==> Activation helper written to activate_env.sh"

# ── Verification ──────────────────────────────────────────────────────────────
echo ""
echo "==> Verifying installation"
python - <<'EOF'
import torch, numpy, sklearn, yaml, scipy, tqdm
print(f"  torch      : {torch.__version__}  (CUDA available: {torch.cuda.is_available()})")
if torch.cuda.is_available():
    print(f"  CUDA       : {torch.version.cuda}")
    print(f"  GPU        : {torch.cuda.get_device_name(0)}")
print(f"  numpy      : {numpy.__version__}")
print(f"  scikit-learn: {sklearn.__version__}")
EOF

echo ""
echo "╔═══════════════════════════════════════════════════════════════════════╗"
echo "║  ✓  HPC setup complete!                                               ║"
echo "╠═══════════════════════════════════════════════════════════════════════╣"
echo "║  Activate  :  source activate_env.sh                                 ║"
echo "║  OR        :  source ${VENV_DIR}/bin/activate"
echo "║  Submit    :  sbatch submit_job.sh                                    ║"
echo "╚═══════════════════════════════════════════════════════════════════════╝"
