#!/usr/bin/env bash
# =============================================================================
# submit_job.sh — Slurm job submission for CINECA (Leonardo / Galileo100)
#                 and generic HPC clusters.
#
# Usage:
#   sbatch submit_job.sh                       # full pipeline (preprocess+train+eval)
#   sbatch --export=ALL,SKIP_PREPROCESS=1 submit_job.sh  # skip download if data exists
#
# Before submitting:
#   1.  Run setup_hpc.sh on the login node to build the venv.
#   2.  Set --account and --partition below for your allocation.
#   3.  Verify module names with:  module av cuda  &&  module av python
# =============================================================================

# ── Slurm directives ──────────────────────────────────────────────────────────
#SBATCH --job-name=jet_anomaly_ae

# Output / error — logs/ must exist; created by setup_hpc.sh or mkdir -p logs
#SBATCH --output=logs/slurm_%j.out
#SBATCH --error=logs/slurm_%j.err

# ---- CINECA Leonardo (A100 GPUs) ----
#SBATCH --partition=boost_usr_prod   # GPU partition on Leonardo
#SBATCH --account=ACCOUNT_CODE       # ← Replace with your CINECA project code
#SBATCH --qos=normal
#SBATCH --gres=gpu:1                 # 1 A100 (80 GB) on Leonardo
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=02:00:00              # HH:MM:SS

# ---- Alternative: CINECA Galileo100 (V100 GPUs) ----
# Uncomment and comment out the Leonardo block above:
##SBATCH --partition=g100_usr_prod
##SBATCH --account=ACCOUNT_CODE
##SBATCH --gres=gpu:1
##SBATCH --qos=normal
##SBATCH --time=02:00:00

# ---- Alternative: Generic GPU cluster ----
##SBATCH --partition=gpu
##SBATCH --gres=gpu:1

# =============================================================================
set -euo pipefail

echo "================================================================"
echo " Job ID   : ${SLURM_JOB_ID}"
echo " Host     : $(hostname)"
echo " Start    : $(date)"
echo " Node(s)  : ${SLURM_JOB_NODELIST}"
echo "================================================================"

# ── Change to the directory where sbatch was called ───────────────────────────
cd "${SLURM_SUBMIT_DIR}"
mkdir -p logs

# ── Load system modules ───────────────────────────────────────────────────────
# CINECA Leonardo module tree (adjust versions as needed):
module purge
module load profile/deeplrn          # sets up deep-learning software stack
module load cuda/11.8                # or cuda/12.1
module load python/3.10.8-gcc11.3    # system Python for venv compatibility

# For Galileo100 use:
# module load profile/deeplrn
# module load cuda/11.8
# module load python/3.8.12-gcc8.5.0

# For a generic cluster without profile modules:
# module load cuda/11.8
# module load python/3.10

# ── Activate virtual environment ──────────────────────────────────────────────
# activate_env.sh is generated by setup_hpc.sh and points to the correct
# scratch location ($CINECA_SCRATCH / $WORK / $SCRATCH).
if [[ -f activate_env.sh ]]; then
    # shellcheck disable=SC1091
    source activate_env.sh
elif [[ -f .venv_path ]]; then
    # shellcheck disable=SC1091
    source "$(grep VENV_DIR .venv_path | cut -d= -f2)/bin/activate"
else
    echo "ERROR: venv not found. Run setup_hpc.sh on the login node first."
    exit 1
fi

# ── GPU diagnostics ───────────────────────────────────────────────────────────
echo "==> GPU info:"
nvidia-smi --query-gpu=name,memory.total,driver_version,cuda_version \
           --format=csv,noheader

echo "==> Python: $(python --version)"
echo "==> PyTorch:"
python -c "import torch; print(f'   {torch.__version__}, CUDA={torch.cuda.is_available()}, device={torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"cpu\"}')"

# ── Pipeline ──────────────────────────────────────────────────────────────────
CONFIG="configs/config.yaml"
GROUP=${GROUP:-37}

# Step 1: Download data (skip if already present)
if [[ "${SKIP_PREPROCESS:-0}" != "1" ]]; then
    echo ""
    echo "==> [1/3] Preprocessing — downloading datasets (group ${GROUP})"
    python scripts/preprocess.py --group "${GROUP}" --data-dir data/raw
else
    echo "==> [1/3] Preprocessing skipped (SKIP_PREPROCESS=1)"
fi

# Step 2: Train
echo ""
echo "==> [2/3] Training"
python scripts/train.py \
    --config "${CONFIG}" \
    --device cuda

# Step 3: Evaluate (no interactive plots on HPC)
echo ""
echo "==> [3/3] Evaluation"
python scripts/evaluate.py \
    --config  "${CONFIG}" \
    --checkpoint checkpoints/ae_best.pt \
    --device cuda \
    --no-plot \
    --no-umap        # UMAP is slow; remove flag if you need it

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "================================================================"
echo " Job complete : $(date)"
echo " Logs         : logs/slurm_${SLURM_JOB_ID}.out"
echo " Checkpoint   : checkpoints/ae_best.pt"
echo "================================================================"
